"""empty message

Revision ID: c9a380826664
Revises: 3eb669701a65
Create Date: 2021-12-05 20:24:25.145933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a380826664'
down_revision = '3eb669701a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postgres_sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_ts_value', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postgres_sync_logs', schema=None) as batch_op:
        batch_op.drop_column('last_sync_ts_value')

    # ### end Alembic commands ###
