"""empty message

Revision ID: 3eb669701a65
Revises: 
Create Date: 2021-12-05 11:16:23.350878

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3eb669701a65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postgres_sync_logs',
                    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=True),
                    sa.Column('global_uuid', sa.String(length=80), nullable=False),
                    sa.Column('last_sync_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('global_uuid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postgres_sync_logs')
    # ### end Alembic commands ###
